### ISSUE TITLE
Flask app on Replit?

### ISSUE THREAD

**Issue by gingerbeardman** [carolynz/poetry-camera-rpi#1]
Is the Flask app on Replit coded source?

I don't mind, but I'm wondering if it's using ChatGPT (3.5?) to generate the poem?

Thanks! Very cool project

**Comment by carolynz** [comment]
Hi, sorry for not seeing this earlier. The Flask app is not yet open source; I just haven't had the time to clean it up. It's just using ChatGPT to generate the poem, and a captioning model to get captions for the image.

**Comment by gingerbeardman** [comment]
No worries! Cheers

**Comment by carolynz** [comment]
I just migrated the model API requests to be made client-side. Just set up a .env with your own API keys 🙏
